config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :salaries

app/models/salary.rb
class Salary < ActiveRecord::Base
end

app/controllers/salaries_controller.rb
class SalariesController < ApplicationController

  def index
  	@salary = Salary.new
  	@time_t = TimeEntry.all
  	@pro = Project.all
    if Salary.exists?
      @project_name = Salary.last.Project
      @project_year = Salary.last.Date_from
      @project_month = Salary.last.Date_to
      @cost = Salary.last.Cost_per_hour
      @count =0
      #search for the values through project and date
      @time_t.each do |tt|
        if tt.project_id == @project_name && tt.spent_on.between?(@project_year,@project_month) 
          @count=@count+tt.hours  
        end
      end
      @count1 = @count*@cost
      @count2 = @count*@cost*0.02
      @count3 = @count*@cost*1.45

      #Replace the name of the project in the table
      @pro.each do |pp|
        if pp.id ==@project_name
          @name = pp.name
          break
        end
      end

#Initial Value
    else
      @count = "Null"
      @count1 = "Null"
      @count2 = "Null"
      @count3 = "Null"
      @name = "Null"
      @cost = "Null"
    end
    # PDF converter
       respond_to do |format|
      	format.html
      	format.pdf do
	      	pdf = MemberPdf.new(@name,@count,@cost,@count1,@count2,@count3)
	      	send_data pdf.render, filename: 'member.pdf', type: 'application/pdf',disposition: "inline"
      	end   
      end
  end

  def create
    @salary = Salary.new(salary_params)
    @salary.save
    redirect_to :back
    

  end

  private
  def salary_params
    params.require(:salary).permit(:Project, :Cost_per_hour, :Date_from, :Date_to)
  end
  end

app/helpers/salaries_helper.rb
module SalariesHelper
end

app/views/salaries/index.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>

<body style="color:blue;">

<div class="col-sm-1 sidenav">
  <button type="button" class="btn-info" data-toggle="collapse" data-target="#demo">New</button>
</div>
<br><br>
<div id="demo" class="collapse">
  <%= bootstrap_form_for (@salary) do |f| %>
    <div class="col-sm-3 sidenav">
      <%= f.select :Project, @pro.map { |e| [e.name , e.id] },{ label: "Project", wrapper: { class: 'has-warning', data: { foo: 'bar' } } }, { class: "selectpicker" } %>  
      <%= f.number_field :Cost_per_hour, min:0 , :value => 0%>  
    </div>
    
    <div class="col-sm-3 sidenav">
      <%= f.date_field :Date_from,:value => Time.now.strftime("%Y-%m-%d")%>
      <%= f.date_field :Date_to,:value => Time.now.strftime("%Y-%m-%d")%>
    </div>
    <br><br><br><br><br>
    <div class="btn" >  <%= f.submit "Search" %> </div>
          
  <% end %>
</div>

  
  <div class="col-sm-9">  
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
          <th>Amount</th>
          <th></th>
          
        </tr>
        <tr>
          <th>Project</th>
          <th>Working Hrs</th>
          <th>Cost/hrs</th>
          <th>YEN</th>
          <th>USD</th>
          <th>NU</th>
          
        </tr>
      </thead>
      <tbody>
        <% if Salary.exists?%>
          <tr>
            <td><%= @name%></td>
            <td><%= @count%></td>
            <td><%= @cost%></td>
            <td><%= @count1 %></td>
            <td><%= @count2 %></td>
            <td><%= @count3 %></td>
          </tr>
        <%else%>
          <tr>
            <td>Null</td>
            <td>Null</td>
            <td>Null</td>
            <td>Null</td>
            <td>Null</td>
            <td>Null</td>
          </tr>
          <%end%>

      </tbody>
    </table>
  </div>
  </body>
  <footer class="col-sm-9" >
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <% if Salary.exists?%>
      <span class="glyphicon glyphicon-download"></span><%= link_to "PDF File",salaries_path(format: 'pdf') %>
      
      <% end %>
  </footer>
</div>
</html>